### PR TITLE
Some improvements to host option

### PR DESCRIPTION
**Pull request by dpprdan**
I improved my first attempt a bit. This now...

1. uses `.onLoad` instead of `.onAttach`. Otherwise e.g. `rmapzen::mz_search()` wouldn't work (I think) without attaching ´rmapzen` (i.e. call `library(rmapzen)`) first. 
2. only sets options if they are not already available, i.e. it does not override existing options. That way one can set `options()` before loading `rmapzen`. -> one can set the `rmapzen` host more permanently in `.Rprofile` for example - in case one regularly uses the same host. 
3. adds `RMAPZEN.matrix.host` and `RMAPZEN.tile.host`.

I am not sure whether it is safe to assume that the `endpoint`/`vector_path` is alway the same over different hosts (e.g. local Pelias installs) and so whether there should also be options for that (or just one combined `host/endpoint` optoin). But perhaps let's just see first how this pans out.

### CODE REVIEW

**Comment by dpprdan** [comment]
The option names seem weird to me now. They should use underscore instead of point like the rest of the package and be either all upper-case like MAPZEN_KEY or lower_case like most other `options()`. What do you think?

**Comment by tarakc02** [comment]
I like the consistency of underscore. I'd vote for the upper-case (so "RMAPZEN_SEARCH_HOST" etc). And yeah, there are a few places where the URL seems implementation-specific -- at that point it seems like it would make sense to keep all host/endpoint configurations in one object. I'm hoping the existing design, where building the URL is split out with `*_path` and `*_url` functions, will make that an easy thing to accommodate. I don't have a geocode.earth account or access to any other pelias install to test different stuff  or have a sense of what different forms the request URLs will take, have you seen other examples?

**Comment by dpprdan** [comment]
I changed the options to `RMAPZEN_SEARCH_HOST` and similar. This suffices to work with [geocode.earth](https:://geocode.earth). (You can request an invite from geocode.earth BTW, which is still free at the moment.)

``` r
library(rmapzen)
# set new search api host
options(RMAPZEN_SEARCH_HOST = "api.geocode.earth")
# set geocode.earth search key
Sys.setenv("MAPZEN_KEY" = Sys.getenv("GEOCODE_EARTH_KEY"))

mz_geocode("1600 Pennsylvania Ave., Washington DC")
#> # A tibble: 1 x 4
#>   geocode_address      geocode_longitude geocode_latitude geocode_confide~
#> * <chr>                            <dbl>            <dbl>            <dbl>
#> 1 District of Columbi~             -77.0             38.9            0.300
mz_search("Hard Rock Cafe", boundary.country = "SE")
#> GeoJSON response from Mapzen
#> Attribution info: http://pelias.mapzen.com/v1/attribution 
#> Bounds (lon/lat): (11.97, 55.78) - (18.05, 62.39)
#> 10 locations:
#>    Hard Rock Café (18.05, 59.34)
#>    Hard Rock Cafe (11.97, 57.7)
#>    Rock'n Roll Café (13.83, 55.93)
#>    Carolas Cafe (13.1, 55.78)
#>    Cafe capri (17.95, 59.4)
#>   ...
```

I cannot test tiles and isochrones since those do not have a (working) new home, yet. 

I have looked into the other possible options (endpoint, path, rate limits depending on API package, API-key, ...). This looks a bit more involved and it would clutter the options IMO, if we would add it like I did now. I like the approach of ggmap (v. 2.7), with all ggmap options [grouped in a list](https://github.com/dkahle/ggmap/blob/master/R/zzz.R) that can be [set](https://github.com/dkahle/ggmap/blob/master/R/register_google.R) and [read](https://github.com/dkahle/ggmap/blob/master/R/ggmap_credentials.R) with custom functions. With the future of the former Mapzen services still in the balance, I am not sure if it is worth it to tackle this right now, though. (I am also a bit short on time).

What are your plans with the package anyway? Split it up in three (search, isochrone, tiles) or just focus on search?

**Comment by tarakc02** [comment]
Thank you! 
As for plans -- I'll add warnings to the isochrone/tiles functions for now and focus on search. Those other services were nice -- if another provider comes along offering them I'll update the package accordingly.

**Comment by drewda** [comment]
@tarakc02 FYI, Mapzen-style tiles are now available at https://developers.nextzen.org/ I can keep you posted on isochrone options.

**Pull request merged**
